# Generated by Django 3.2.9 on 2021-12-08 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, 'Quantity should be >=0')]),
            preserve_default=False,
        ),
    ]
