# Generated by Django 3.2.9 on 2021-12-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(default='Nur ein Tets'),
            preserve_default=False,
        ),
    ]
