# Generated by Django 3.2.5 on 2021-12-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_text2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text2',
            new_name='text3',
        ),
    ]
