# Generated by Django 3.2.9 on 2021-12-08 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testtable',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text3',
        ),
        migrations.AlterField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Quantity should be >=0')]),
        ),
    ]
