# Generated by Django 3.2.9 on 2021-12-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211208_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('NW', 'Nachrichten'), ('AR', 'Artikel')], default='AR', max_length=2),
        ),
    ]
