# Generated by Django 3.2.9 on 2022-01-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20220108_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='user_email',
        ),
    ]
